Fix trying to get index of Nonetype
Minor fix to stop trying to get the index of a None value when you've set remove_duplicates to True

AttributeError: 'NoneType' object has no attribute 'index'